title: Atomic Lyrics
email: you@example.com
description: >- 
  A minimal personal blog powered by Jekyll.
baseurl: ""
url: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
